"""add platform assistant conversations

Revision ID: 07468d4d9da8
Revises: 20260726_0011
Create Date: 2026-07-26 18:38:20.300487
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "07468d4d9da8"
down_revision: str | Sequence[str] | None = "20260726_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_conversations",
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("runtime_provider", sa.String(length=32), nullable=False),
        sa.Column("runtime_thread_id", sa.String(length=100), nullable=True),
        sa.Column("runtime_workspace_id", sa.String(length=100), nullable=True),
        sa.Column("runtime_workspace_path", sa.String(length=1024), nullable=True),
        sa.Column("runtime_thread_generation", sa.Integer(), nullable=False),
        sa.Column("observed_compactions", sa.Integer(), nullable=False),
        sa.Column("tool_contract_version", sa.String(length=20), nullable=False),
        sa.Column("system_prompt_version", sa.String(length=128), nullable=False),
        sa.Column("rolling_summary", sa.Text(), nullable=True),
        sa.Column("last_message_sequence", sa.Integer(), nullable=False),
        sa.Column("last_event_sequence", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'archived')",
            name=op.f("ck_assistant_conversations_valid_status"),
        ),
        sa.CheckConstraint(
            "runtime_thread_generation >= 0 AND observed_compactions >= 0",
            name=op.f("ck_assistant_conversations_nonnegative_thread_counters"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_assistant_conversations_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "conversation_id", name=op.f("pk_assistant_conversations")
        ),
        sa.UniqueConstraint(
            "runtime_thread_id",
            name=op.f("uq_assistant_conversations_runtime_thread_id"),
        ),
    )
    op.create_index(
        op.f("ix_assistant_conversations_owner_user_id"),
        "assistant_conversations",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "assistant_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["assistant_conversations.conversation_id"],
            name=op.f("fk_assistant_events_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_assistant_events_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_assistant_events")),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_assistant_events_sequence"
        ),
    )
    op.create_index(
        op.f("ix_assistant_events_aggregate_id"),
        "assistant_events",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_events_conversation_id"),
        "assistant_events",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_events_correlation_id"),
        "assistant_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_events_event_type"),
        "assistant_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_events_owner_user_id"),
        "assistant_events",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "assistant_messages",
        sa.Column("message_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("text_content", sa.Text(), nullable=False),
        sa.Column("content_blocks", sa.JSON(), nullable=False),
        sa.Column("attachment_refs", sa.JSON(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=True),
        sa.Column("reply_to_message_id", sa.String(length=36), nullable=True),
        sa.Column("related_resource_type", sa.String(length=50), nullable=True),
        sa.Column("related_resource_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "role IN ('user', 'assistant', 'event')",
            name=op.f("ck_assistant_messages_valid_role"),
        ),
        sa.CheckConstraint(
            "status IN ('accepted', 'completed', 'failed')",
            name=op.f("ck_assistant_messages_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["assistant_conversations.conversation_id"],
            name=op.f("fk_assistant_messages_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_assistant_messages_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("message_id", name=op.f("pk_assistant_messages")),
        sa.UniqueConstraint(
            "conversation_id",
            "idempotency_key",
            name="uq_assistant_messages_idempotency",
        ),
        sa.UniqueConstraint(
            "conversation_id", "sequence", name="uq_assistant_messages_sequence"
        ),
    )
    op.create_index(
        op.f("ix_assistant_messages_conversation_id"),
        "assistant_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_messages_owner_user_id"),
        "assistant_messages",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "assistant_turns",
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("source_message_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("runtime_provider", sa.String(length=32), nullable=False),
        sa.Column("runtime_thread_generation", sa.Integer(), nullable=False),
        sa.Column("runtime_thread_id", sa.String(length=100), nullable=True),
        sa.Column("runtime_turn_id", sa.String(length=100), nullable=True),
        sa.Column("runtime_job_id", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_model", sa.String(length=100), nullable=True),
        sa.Column("actual_model", sa.String(length=100), nullable=True),
        sa.Column("reasoning_effort", sa.String(length=32), nullable=True),
        sa.Column("final_message_id", sa.String(length=36), nullable=True),
        sa.Column("failure_code", sa.String(length=100), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("cached_input_tokens", sa.BigInteger(), nullable=True),
        sa.Column("output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("reasoning_output_tokens", sa.BigInteger(), nullable=True),
        sa.Column("total_tokens", sa.BigInteger(), nullable=True),
        sa.Column("context_compactions", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'submitted', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_assistant_turns_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["assistant_conversations.conversation_id"],
            name=op.f("fk_assistant_turns_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_assistant_turns_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_message_id"],
            ["assistant_messages.message_id"],
            name=op.f("fk_assistant_turns_source_message_id_assistant_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("turn_id", name=op.f("pk_assistant_turns")),
        sa.UniqueConstraint(
            "conversation_id", "idempotency_key", name="uq_assistant_turns_idempotency"
        ),
        sa.UniqueConstraint(
            "source_message_id", name=op.f("uq_assistant_turns_source_message_id")
        ),
    )
    op.create_index(
        op.f("ix_assistant_turns_conversation_id"),
        "assistant_turns",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_turns_execution_id"),
        "assistant_turns",
        ["execution_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_assistant_turns_owner_user_id"),
        "assistant_turns",
        ["owner_user_id"],
        unique=False,
    )
    op.create_table(
        "assistant_actions",
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("conversation_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("source_turn_id", sa.String(length=36), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("proposed_at", sa.DateTime(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('proposed', 'confirmed', 'executing', 'completed', 'failed', 'declined', 'cancelled', 'expired', 'superseded')",
            name=op.f("ck_assistant_actions_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["assistant_conversations.conversation_id"],
            name=op.f("fk_assistant_actions_conversation_id_assistant_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_assistant_actions_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_turn_id"],
            ["assistant_turns.turn_id"],
            name=op.f("fk_assistant_actions_source_turn_id_assistant_turns"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_assistant_actions")),
        sa.UniqueConstraint(
            "conversation_id",
            "idempotency_key",
            name="uq_assistant_actions_idempotency",
        ),
    )
    op.create_index(
        op.f("ix_assistant_actions_conversation_id"),
        "assistant_actions",
        ["conversation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_actions_owner_user_id"),
        "assistant_actions",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assistant_actions_source_turn_id"),
        "assistant_actions",
        ["source_turn_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assistant_actions_source_turn_id"), table_name="assistant_actions"
    )
    op.drop_index(
        op.f("ix_assistant_actions_owner_user_id"), table_name="assistant_actions"
    )
    op.drop_index(
        op.f("ix_assistant_actions_conversation_id"), table_name="assistant_actions"
    )
    op.drop_table("assistant_actions")
    op.drop_index(
        op.f("ix_assistant_turns_owner_user_id"), table_name="assistant_turns"
    )
    op.drop_index(op.f("ix_assistant_turns_execution_id"), table_name="assistant_turns")
    op.drop_index(
        op.f("ix_assistant_turns_conversation_id"), table_name="assistant_turns"
    )
    op.drop_table("assistant_turns")
    op.drop_index(
        op.f("ix_assistant_messages_owner_user_id"), table_name="assistant_messages"
    )
    op.drop_index(
        op.f("ix_assistant_messages_conversation_id"), table_name="assistant_messages"
    )
    op.drop_table("assistant_messages")
    op.drop_index(
        op.f("ix_assistant_events_owner_user_id"), table_name="assistant_events"
    )
    op.drop_index(op.f("ix_assistant_events_event_type"), table_name="assistant_events")
    op.drop_index(
        op.f("ix_assistant_events_correlation_id"), table_name="assistant_events"
    )
    op.drop_index(
        op.f("ix_assistant_events_conversation_id"), table_name="assistant_events"
    )
    op.drop_index(
        op.f("ix_assistant_events_aggregate_id"), table_name="assistant_events"
    )
    op.drop_table("assistant_events")
    op.drop_index(
        op.f("ix_assistant_conversations_owner_user_id"),
        table_name="assistant_conversations",
    )
    op.drop_table("assistant_conversations")
    # ### end Alembic commands ###
