"""create task execution and event tables

Revision ID: 39bba66c6ae1
Revises: 20260723_0002
Create Date: 2026-07-24 00:10:28.571180
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "39bba66c6ae1"
down_revision: Union[str, Sequence[str], None] = "20260723_0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("owner_user_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("organization_spec_version_id", sa.String(length=36), nullable=False),
        sa.Column("request_text", sa.Text(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('created', 'planning', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_tasks_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.organization_id"],
            name=op.f("fk_tasks_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_spec_version_id"],
            ["organization_spec_versions.spec_version_id"],
            name=op.f(
                "fk_tasks_organization_spec_version_id_organization_spec_versions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.user_id"],
            name=op.f("fk_tasks_owner_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("task_id", name=op.f("pk_tasks")),
        sa.UniqueConstraint(
            "owner_user_id",
            "organization_id",
            "idempotency_key",
            name="uq_tasks_owner_organization_idempotency_key",
        ),
    )
    op.create_index(
        op.f("ix_tasks_organization_id"), "tasks", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_tasks_organization_spec_version_id"),
        "tasks",
        ["organization_spec_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tasks_owner_user_id"), "tasks", ["owner_user_id"], unique=False
    )
    op.create_index(op.f("ix_tasks_status"), "tasks", ["status"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("agent_role_key", sa.String(length=64), nullable=False),
        sa.Column("instructions", sa.Text(), nullable=False),
        sa.Column("acceptance_criteria", sa.Text(), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'submitted', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_assignments_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_assignments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("assignment_id", name=op.f("pk_assignments")),
        sa.UniqueConstraint("execution_id", name="uq_assignments_execution_id"),
        sa.UniqueConstraint(
            "task_id", "agent_role_key", name="uq_assignments_task_role_key"
        ),
    )
    op.create_index(
        op.f("ix_assignments_status"), "assignments", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_assignments_task_id"), "assignments", ["task_id"], unique=False
    )
    op.create_table(
        "product_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("aggregate_type", sa.String(length=50), nullable=False),
        sa.Column("aggregate_id", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("assignment_id", sa.String(length=36), nullable=True),
        sa.Column("runtime_execution_id", sa.String(length=36), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("correlation_id", sa.String(length=100), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.task_id"],
            name=op.f("fk_product_events_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_product_events")),
        sa.UniqueConstraint(
            "task_id", "sequence", name="uq_product_events_task_sequence"
        ),
    )
    op.create_index(
        op.f("ix_product_events_aggregate_id"),
        "product_events",
        ["aggregate_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_events_correlation_id"),
        "product_events",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_events_event_type"),
        "product_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_events_task_id"), "product_events", ["task_id"], unique=False
    )
    op.create_table(
        "runtime_executions",
        sa.Column("runtime_execution_id", sa.String(length=36), nullable=False),
        sa.Column("execution_id", sa.String(length=36), nullable=False),
        sa.Column("assignment_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("runtime_job_id", sa.String(length=100), nullable=True),
        sa.Column("thread_id", sa.String(length=100), nullable=True),
        sa.Column("turn_id", sa.String(length=100), nullable=True),
        sa.Column("workspace_id", sa.String(length=36), nullable=True),
        sa.Column("last_event_position", sa.String(length=100), nullable=True),
        sa.Column("result_summary", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "status IN ('submitted', 'running', 'waiting', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_runtime_executions_valid_status"),
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["assignments.assignment_id"],
            name=op.f("fk_runtime_executions_assignment_id_assignments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "runtime_execution_id", name=op.f("pk_runtime_executions")
        ),
    )
    op.create_index(
        op.f("ix_runtime_executions_assignment_id"),
        "runtime_executions",
        ["assignment_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_runtime_executions_execution_id"),
        "runtime_executions",
        ["execution_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_runtime_executions_status"),
        "runtime_executions",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runtime_executions_status"), table_name="runtime_executions")
    op.drop_index(
        op.f("ix_runtime_executions_execution_id"), table_name="runtime_executions"
    )
    op.drop_index(
        op.f("ix_runtime_executions_assignment_id"), table_name="runtime_executions"
    )
    op.drop_table("runtime_executions")
    op.drop_index(op.f("ix_product_events_task_id"), table_name="product_events")
    op.drop_index(op.f("ix_product_events_event_type"), table_name="product_events")
    op.drop_index(op.f("ix_product_events_correlation_id"), table_name="product_events")
    op.drop_index(op.f("ix_product_events_aggregate_id"), table_name="product_events")
    op.drop_table("product_events")
    op.drop_index(op.f("ix_assignments_task_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_status"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_tasks_status"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_owner_user_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_organization_spec_version_id"), table_name="tasks")
    op.drop_index(op.f("ix_tasks_organization_id"), table_name="tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
